name: Scrape and push 

on: 
  schedule: 
    # - cron: "0 0 * * *"
    # runs daily at midnight
    - cron: '* * * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Scrape
        run: ./update-scraper.sh
        shell: bash
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."